CREATE DATABASE PantryPalDB;

Use PantryPalDB

CREATE TABLE Users (
	UserId INT IDENTITY(1,1) PRIMARY KEY,
	Username NVARCHAR(100) NOT NULL UNIQUE, 
	Email NVARCHAR(100) NOT NULL UNIQUE, 
	PasswordHash VARBINARY (255) NOT NULL
);
CREATE TABLE PantryItem (
	ItemId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	ItemName NVARCHAR(100) NOT NULL,
	Quantity INT NOT NULL,
	UnitOfMeasure NVARCHAR(50) NOT NULL,
	ExpirationDate DATE NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(UserId)	
);
CREATE TABLE Favorites (
	FavoriteId INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	RecipeName NVARCHAR(100),
	RecipeUrl NVARCHAR(MAX),
	RecipeImage NVARCHAR(MAX),
	FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE TABLE FoodWasteStats (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ItemsWasted INT DEFAULT 0,
	ItemsUsed INT DEFAULT 0,
	UserId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

